import { VideoSource, DiagnosisResult, QualityMetrics } from '@/store/nova-store';

export interface DemoPreset {
  id: string;
  title: string;
  category: string;
  badge: string;
  description: string;
  videoUrl: string;
  thumbnail: string;
  source: VideoSource;
  diagnosis: DiagnosisResult;
  metrics: QualityMetrics;
}

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: 'cyberpunk-neon',
    title: 'Cyberpunk Sci-Fi VFX',
    category: 'VFX / 4K Upscale',
    badge: '4K HDR Remaster',
    description: 'High-speed sci-fi action restored from noisy 720p to crystal-sharp 4K 60fps HDR with AI motion stabilization.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    source: {
      name: 'Tears_of_Steel_Cyberpunk_720p.mp4',
      size: 48 * 1024 * 1024,
      type: 'video/mp4',
      duration: '00:45',
      resolution: '1280x720',
      width: 1280,
      height: 720,
      fps: 24,
      codec: 'H.264 Main@L3.1',
      bitrate: '2.8 Mbps',
      audioCodec: 'AAC 128kbps',
      objectUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    },
    diagnosis: {
      compression: 'high',
      noise: 'medium',
      blur: 'medium',
      blurType: 'motion',
      faces: 3,
      faceQuality: 'medium',
      textDetected: true,
      textRegions: 2,
      lowLight: 'medium',
      exposure: 0.85,
      dynamicRange: 'low',
      isAnime: false,
      overallQuality: 54,
      recommendedPipeline: ['temporal_denoise', 'super_resolution_4x', 'face_refinement', 'hdr_tonemap'],
      warnings: ['Heavy motion blur in action sequences', 'Dark shadow clipping in neon alleys'],
    },
    metrics: {
      psnr: 68.4,
      ssim: 78.2,
      vmaf: 84.6,
      temporalConsistency: 89.1,
      faceStability: 96.2,
      edgeStability: 85.3,
      artifactScore: 82.0,
    },
  },
  {
    id: 'vintage-archival',
    title: '1920s Archival Film Restoration',
    category: 'Film Heritage',
    badge: 'Scratch & Grain Removal',
    description: 'Vintage 35mm celluloid film with severe jitter, flicker, dust particles, and nitrate film degradation restored to pristine 4K.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    source: {
      name: 'Archival_Vintage_1928_Footage.mp4',
      size: 32 * 1024 * 1024,
      type: 'video/mp4',
      duration: '00:30',
      resolution: '640x480',
      width: 640,
      height: 480,
      fps: 18,
      codec: 'MPEG-4 Part 2',
      bitrate: '1.4 Mbps',
      audioCodec: 'Mono Optical 64kbps',
      objectUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    },
    diagnosis: {
      compression: 'critical',
      noise: 'critical',
      blur: 'high',
      blurType: 'defocus',
      faces: 2,
      faceQuality: 'low',
      textDetected: false,
      textRegions: 0,
      lowLight: 'high',
      exposure: 0.65,
      dynamicRange: 'low',
      isAnime: false,
      overallQuality: 38,
      recommendedPipeline: ['scratch_dust_removal', 'film_flicker_stabilize', 'super_resolution_4x', 'ai_colorization'],
      warnings: ['High frame flicker rate (18fps jitter)', 'Nitrate film grain saturation'],
    },
    metrics: {
      psnr: 72.1,
      ssim: 81.5,
      vmaf: 86.8,
      temporalConsistency: 92.4,
      faceStability: 94.0,
      edgeStability: 88.7,
      artifactScore: 89.2,
    },
  },
  {
    id: 'anime-remaster',
    title: '480p Classic Animation Remaster',
    category: 'Animation / Anime',
    badge: 'Vector Sharp 4K',
    description: 'Low-res anime with color bleeding, interlacing comb artifacts, and blurred linework reconstructed with neural vector line art sharpening.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    source: {
      name: 'Retro_Anime_Ep01_480p_DVD.mp4',
      size: 26 * 1024 * 1024,
      type: 'video/mp4',
      duration: '00:50',
      resolution: '720x480',
      width: 720,
      height: 480,
      fps: 23.976,
      codec: 'MPEG-2 DVD',
      bitrate: '2.1 Mbps',
      audioCodec: 'AC3 2.0 192kbps',
      objectUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    },
    diagnosis: {
      compression: 'high',
      noise: 'low',
      blur: 'high',
      blurType: 'defocus',
      faces: 4,
      faceQuality: 'medium',
      textDetected: true,
      textRegions: 3,
      lowLight: 'none',
      exposure: 1.0,
      dynamicRange: 'normal',
      isAnime: true,
      overallQuality: 49,
      recommendedPipeline: ['anime_line_art_refine', 'deinterlace_yadif', 'waifu2x_neural_4x', 'color_gamut_expand'],
      warnings: ['DVD compression DCT ringing around contours'],
    },
    metrics: {
      psnr: 76.8,
      ssim: 88.4,
      vmaf: 91.2,
      temporalConsistency: 94.7,
      faceStability: 98.1,
      edgeStability: 95.0,
      artifactScore: 92.5,
    },
  },
  {
    id: 'vhs-family-camcorder',
    title: '1994 VHS Magnetic Camcorder',
    category: 'Home Video / VHS',
    badge: 'Deinterlace & 60FPS',
    description: 'Analog magnetic tape noise, chroma shift, head-switching lines, and 240-line horizontal resolution restored to smooth 1080p 60fps.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail: 'https://images.unsplash.com/photo-1518173946687-a4c8a383392e?w=600&auto=format&fit=crop&q=80',
    source: {
      name: 'Family_Vacation_Summer_1994_VHS.mp4',
      size: 55 * 1024 * 1024,
      type: 'video/mp4',
      duration: '00:40',
      resolution: '640x480',
      width: 640,
      height: 480,
      fps: 29.97,
      codec: 'DV NTSC',
      bitrate: '3.5 Mbps',
      audioCodec: 'Linear PCM Mono',
      objectUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    },
    diagnosis: {
      compression: 'medium',
      noise: 'critical',
      blur: 'high',
      blurType: 'mixed',
      faces: 5,
      faceQuality: 'low',
      textDetected: true,
      textRegions: 1,
      lowLight: 'medium',
      exposure: 0.78,
      dynamicRange: 'low',
      isAnime: false,
      overallQuality: 42,
      recommendedPipeline: ['vhs_chroma_alignment', 'head_switching_crop', 'rife_interpolation_60fps', 'neural_face_gfpgan'],
      warnings: ['Analog magnetic tape dropouts', 'Severe chroma-luma phase shift'],
    },
    metrics: {
      psnr: 71.0,
      ssim: 79.9,
      vmaf: 83.2,
      temporalConsistency: 91.8,
      faceStability: 93.4,
      edgeStability: 86.1,
      artifactScore: 84.3,
    },
  },
];
